name: Build Multi-Platform Releases

on:
  push:
    tags:
      - 'v*'  # Ejecutar cuando se cree un tag de versión
  workflow_dispatch:  # Permitir ejecución manual

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            artifact_name: ConversorMultimedia.exe
          - os: macos-latest
            platform: macos
            artifact_name: ConversorMultimedia.app
          - os: ubuntu-latest
            platform: linux
            artifact_name: ConversorMultimedia

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Build executable
      run: |
        cd src
        python build_exe.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: conversor-multimedia-${{ matrix.platform }}
        path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Display structure of downloaded files
      run: ls -la artifacts/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*/*
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## 🎉 Nueva versión del Conversor Multimedia
          
          ### Descargas por plataforma:
          - 🪟 **Windows**: ConversorMultimedia.exe
          - 🍎 **macOS**: ConversorMultimedia.app  
          - 🐧 **Linux**: ConversorMultimedia
          
          ### Características:
          - ✅ Conversión de imágenes, videos y audio
          - ✅ **NUEVO**: Conversión de video a GIF
          - ✅ Interfaz gráfica intuitiva
          - ✅ Procesamiento por lotes
          - ✅ Sin dependencias adicionales
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
